- name: Download Erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: Download rabbitmq package
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install Erlang and Rabbitmq server
  ansible.builtin.yum:
    name:
      - erlang
      - rabbitmq-server
    state: installed

- name: Start Rabbitmq service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Adding Application user
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('amazon.aws.aws_ssm', '{{ env }}.{{ component }}.amqp_user', region='us-east-1') }}"
    password: "{{ lookup('amazon.aws.aws_ssm', '{{ env }}.{{ component }}.amqp_pass', region='us-east-1') }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*