- name: Download NodeJs Repo file
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash


- name: Installing NodeJs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import Application Prerequisites
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install npm package
  community.general.npm:
    name: npm
    path: /app

- name: Loading Schema setup
  ansible.builtin.import_tasks:
    file: schema-setup.yml

- name: SystemD setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml