- name: Install Python, GCC
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Setting Application Prerequisites
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install python dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
#    executable: pip3.6

- name: setup systemD
  ansible.builtin.import_tasks:
    file: systemd-setup.yml
