#if [ "${schema_type}" == "mongo" ]; then
#print_head "Copying MONGODB repo file  "
#cp ${code_dir}/configs/mongodb.repo /etc/yum.repos.d/mongo.repo &>>${log_file}
#status_check $?
#
#print_head "Installing MongoDB client "
#yum install mongodb-org-shell -y &>>${log_file}
#status_check $?
#
#print_head "Load MongoDB database"
#mongo --host mongodb-dev.devops-practice.tech </app/schema/${component}.js &>>${log_file}
#status_check $?
#elif [ "${schema_type}" == "mysql" ]; then
#print_head "Installing mysql "
#yum install mysql -y &>>${log_file}
#status_check $?
#
#print_head "Connecting mysql database"
#mysql -h mysql-dev.devops-practice.tech -uroot -p${mysql_root_password} < /app/schema/${component}.sql &>>${log_file}
#status_check $?

- name: Mongodb schema
  when: schema_type == "mongo"
  block:
  - name: Copying Mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.db

  - name: Install Mongodb client
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: Load Mongodb database
    ansible.builtin.shell: mongo --host mongodb-dev.devops-practice.tech </app/schema/{{ component }}.js

- name: Mysql schema
  when: schema_type == "mysql"
  block:
    - name: Install Mysql client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load mysql database
      ansible.builtin.shell: mysql -h mysql-dev.devops-practice.tech -uroot -pRoboshop@1 < /app/schema/{{ component }}.sql